%RUN_DB_GROUP_TRACKING_SUBPLOTS  Plot tracking errors for multiple filter groups.
%   Edit the filterGroups block below to define multiple selections, then run
%   this script to plot tracking error subplots for each group.

close all

%% Parameter block (edit these)
% Default database path if left empty.
databaseFile = '';

% Define multiple groups of filters to plot on separate subplots.
filterGroups = {
    struct( ...
        'scenarioNames', {}, ...
        'trajectoryTypes', {'line'}, ...
        'trajectoryProfiles', {}, ...
        'controllerTypes', {'lqr'}, ...
        'controllerProfiles', {}, ...
        'solverPresets', {'balanced'}, ...
        'title', 'Line LQR - Balanced')
    struct( ...
        'scenarioNames', {}, ...
        'trajectoryTypes', {'line'}, ...
        'trajectoryProfiles', {}, ...
        'controllerTypes', {'lqr'}, ...
        'controllerProfiles', {}, ...
        'solverPresets', {'accurate'}, ...
        'title', 'Line LQR - Accurate')
    };

showLegend = true;

%% Build options and call the helper
args = { ...
    'showLegend', showLegend ...
    };

plotRunGroupTrackingSubplotsFromDatabase(databaseFile, filterGroups, args{:});
